 image: docker:stable

 services:
   - docker:dind

 before_script:
   - docker info

 build:
   stage: build
   script:
     - docker build -t registry.gitlab.com/8398a7/abilitysheet:latest .
     - docker images
