# ネストが深すぎる
BlockNesting:
  Max: 5

# クラスの行数が多すぎる
ClassLength:
  Enabled: false

# 循環的複雑度が高すぎる(ifやforなどを1メソッド内で使いすぎている)
CyclomaticComplexity:
  Enabled: false

# 例外を抑制している
HandleExceptions:
  Enabled: false

# 行が長すぎる
LineLength:
  Enabled: false

# メソッドの行数が多すぎる
MethodLength:
  Enabled: false

# 引数の数が多すぎる
ParameterLists:
  Max: 12

Metrics/ModuleLength:
  Max: 200

AccessorMethodName:
  Enabled: false

Metrics/AbcSize:
  Max: 40

PerceivedComplexity:
  Max: 10

BlockLength:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile'
    - 'db/**/*'
    - 'bin/*'
    - 'Capfile'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
