# ネストが深すぎる
Metrics/BlockNesting:
  Max: 5

# クラスの行数が多すぎる
Metrics/ClassLength:
  Enabled: false

# 循環的複雑度が高すぎる(ifやforなどを1メソッド内で使いすぎている)
Metrics/CyclomaticComplexity:
  Enabled: false

# 例外を抑制している
Lint/SuppressedException:
  Enabled: false

# 行が長すぎる
Layout/LineLength:
  Enabled: false

# メソッドの行数が多すぎる
Metrics/MethodLength:
  Enabled: false

# 引数の数が多すぎる
Metrics/ParameterLists:
  Max: 12

Metrics/ModuleLength:
  Max: 200

Naming/AccessorMethodName:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

AllCops:
  NewCops: disable
  TargetRubyVersion: 2.7
  Exclude:
    - 'Gemfile'
    - 'db/**/*'
    - 'bin/*'
    - 'Capfile'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
