# 1行の文字列数
Metrics/LineLength:
  Max: 120

# メソッドの最大行数
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 50

# クラスの最大行数
Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 300

# ASCII文字のコメントを許可
Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

# rails用
Documentation:
  Enabled: false

Metrics/AbcSize:
    Max: 25
