language: ruby
rvm:
  - 2.1.5
sudo: false
cache: bundler
gemfile:
  - Gemfile
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate
env:
  SECRET_KEY_BASE="$(bundle exec rake secret)"
  secret_key_base="$(bundle exec rake secret)"
