language: ruby
rvm:
- 2.1.5
sudo: false
cache: bundler
gemfile:
- Gemfile
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create db:migrate
before_install:
- openssl aes-256-cbc -K $encrypted_b6a8623ba3b4_key -iv $encrypted_b6a8623ba3b4_iv
  -in secrets.yml.enc -out config/secrets.yml -d
