language: ruby

rvm:
  - 2.1.5

gemfile:
  - Gemfile

bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
