language: ruby
rvm:
- 2.2.1
sudo: false
cache: bundler
gemfile:
- Gemfile
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create db:migrate
services:
  - redis-server
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle exec rake tests:integration || false'
