version: '2'
services:
  db:
    image: postgres
  app:
    build: .
    env_file: .env
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/abilitysheet_app
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
  batch:
    build: .
    env_file: .env
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/abilitysheet_batch
    depends_on:
      - db
      - cache
  cache:
    image: redis
