version: '3'

services:
  db:
    image: postgres
    networks:
      - flat-network
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    environment:
      - RAILS_ENV=production
    command: pumactl start
    depends_on:
      - db
      - cache
    volumes:
      - public:/abilitysheet/public
      - puma:/abilitysheet/tmp/sockets
    networks:
      - flat-network

  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - public:/tmp/public
      - puma:/tmp/sockets
    depends_on:
      - app
    networks:
      - flat-network

  batch:
    build: .
    env_file: .env
    environment:
      - RAILS_ENV=production
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - cache
    networks:
      - flat-network

  cache:
    image: redis
    networks:
      - flat-network

volumes:
  db-data:
  public:
  puma:

networks:
  flat-network:
