apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: abilitysheet
spec:
  tls:
  - hosts:
    - localhost
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: puma-service
          servicePort: 3000
