apiVersion: v1
kind: Service
metadata:
  name: {{ template "abilitysheet.puma.name" . }}
  labels:
    app: {{ template "abilitysheet.name" . }}
    chart: {{ template "abilitysheet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puma
spec:
  selector:
    app: {{ template "abilitysheet.name" . }}
    release: {{ .Release.Name }}
    component: puma
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
