apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "abilitysheet.redis.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
    helm.sh/chart: {{ template "abilitysheet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: redis
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  hostPath:
    path: /data
