apiVersion: v1
kind: Service
metadata:
  name: {{ template "abilitysheet.redis.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
    helm.sh/chart: {{ template "abilitysheet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: redis
spec:
  selector:
    app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
