apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "abilitysheet.redis.name" . }}
  labels:
    app: {{ template "abilitysheet.name" . }}
    chart: {{ template "abilitysheet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: redis
spec:
  replicas: {{ .Values.redis.replica }}
  selector:
    matchLabels:
      app: {{ template "abilitysheet.name" . }}
      release: {{ .Release.Name }}
      component: redis
  template:
    metadata:
      labels:
        app: {{ template "abilitysheet.name" . }}
        release: {{ .Release.Name }}
        component: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image.repositry }}:{{ .Values.redis.image.tag }}
        ports:
        - containerPort: 6379
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "abilitysheet.redis.name" . }}
      restartPolicy: Always
