apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "abilitysheet.redis.name" . }}
  labels:
    app: {{ template "abilitysheet.name" . }}
    chart: {{ template "abilitysheet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: redis
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 200Mi
