apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "abilitysheet.redis.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
    helm.sh/chart: {{ template "abilitysheet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 200Mi
