apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "abilitysheet.redis.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
    helm.sh/chart: {{ template "abilitysheet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replica }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
        helm.sh/chart: {{ template "abilitysheet.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image.repositry }}:{{ .Values.redis.image.tag }}
        ports:
        - containerPort: 6379
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "abilitysheet.redis.name" . }}
      restartPolicy: Always
