apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "abilitysheet.sidekiq.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
    helm.sh/chart: {{ template "abilitysheet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: sidekiq
spec:
  replicas: {{ .Values.sidekiq.replica }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: sidekiq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "abilitysheet.name" . }}
        helm.sh/chart: {{ template "abilitysheet.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: {{ .Values.rails.image.repositry }}:{{ .Values.rails.image.tag }}
        command: ["sidekiq", "-C", "config/sidekiq.yml"]
        envFrom:
        - configMapRef:
            name: {{ template "abilitysheet.rails-env.name" . }}
        - secretRef:
            name: {{ template "abilitysheet.rails-env.name" . }}
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "abilitysheet.pg.name" . }}
              key: postgresql-password
      restartPolicy: Always
