version: 2.1

orbs:
  codeclimate: sue445/codeclimate@0.1.0
  ruby-orbs: sue445/ruby-orbs@1.6.0

jobs:
  test-job:
    working_directory: /tmp/abilitysheet
    docker:
      - image: circleci/ruby:3.0.0-rc1-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:@localhost
          TZ: /usr/share/zoneinfo/Asia/Tokyo
      - image: postgres:11.5-alpine
      - image: redis:5.0.5-alpine
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - ruby-orbs/bundle-install
      - run:
          name: Setup Application Environment
          command: mv .env.sample .env && mv config/database.circleci.yml config/database.yml
      - run:
          name: Create DB
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Exec Rubocop
          command: bundle exec bin/rubocop_parallel
      - run:
          name: Exec Eslint And Prettier
          command: yarn lint
      - run:
          name: Generate routes.ts
          command: bundle exec rails ts:routes
      - run:
          name: Create test-results dir
          command: mkdir -p tmp/test-results
      - codeclimate/with-cc-test-reporter:
          after_build_args: '--coverage-input-type simplecov'
          steps:
            - run: bundle exec rspec
      - store_test_results:
          path: ./tmp/test-results
      - store_artifacts:
          path: ./tmp/test-results
          destination: test-results

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test-job
