version: 2
jobs:
  test-job:
    working_directory: /tmp/abilitysheet
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:@localhost
          TZ: /usr/share/zoneinfo/Asia/Tokyo
      - image: postgres:11.4-alpine
      - image: redis:5.0.5-alpine
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - restore_cache:
          name: Restore bundler cache
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: bundle install -j4 --path vendor/bundle
      - save_cache:
          name: Save bundler cache
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Setup Application Environment
          command: mv .env.sample .env && mv config/database.circleci.yml config/database.yml
      - run:
          name: Create DB
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Exec Rubocop
          command: bundle exec bin/rubocop_parallel
      - run:
          name: Exec Tslint
          command: yarn run lint
      - run:
          name: Generate routes.ts
          command: bundle exec rails ts:routes
      - run:
          name: Exec RSpec
          command: bundle exec rspec
      - run:
          name: Report Codeclimate
          command: bundle exec codeclimate-test-reporter
      - run:
          name: Run Puma
          command: mkdir -p tmp/sockets && RAILS_ENV=production bundle exec pumactl start
      - store_artifacts:
          path: ./log/test.log
      - store_artifacts:
          path: ./tmp/screenshots
  build-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          scripts/cloud-build.sh

  sentry-job:
    working_directory: /tmp/abilitysheet
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore bundler cache
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: bundle install -j4 --path vendor/bundle
      - save_cache:
          name: Save bundler cache
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: install sentry cli
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: generate TAG
          command: git describe --tags --abbrev=10 > TAG
      - run:
          name: upload source map
          command: scripts/enable-source-map-precompile.sh

  deploy-job:
    working_directory: /tmp/abilitysheet
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore bundler cache
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: bundle install -j4 --path vendor/bundle
      - save_cache:
          name: Save bundler cache
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Deploy if tests pass and branch is Master
          command: bundle exec cap production deploy

workflows:
  version: 2
  build:
    jobs:
      - build-job:
          filters:
            branches:
              only: master
      - sentry-job:
          filters:
            branches:
              only: master
  test-deploy:
    jobs:
      - test-job
      - deploy-job:
          requires:
            - test-job
            - sentry-job
            - build-job
          filters:
            branches:
              only: master
