apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-claim
  namespace: abilitysheet
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 200Mi
