apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-deployment
  labels:
    app: rails
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: app
        image: registry.gitlab.com/8398a7/abilitysheet
        command: ["puma", "-C", "config/puma.rb"]
        envFrom:
        - configMapRef:
            name: rails-config
        - secretRef:
            name: rails-secret
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            port: 3000
      - name: batch
        image: registry.gitlab.com/8398a7/abilitysheet
        command: ["sidekiq", "-C", "config/sidekiq.yml"]
        envFrom:
        - configMapRef:
            name: rails-config
        - secretRef:
            name: rails-secret
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
