apiVersion: apps/v1
kind: Deployment
metadata:
  name: puma-deployment
  namespace: abilitysheet
  labels:
    app: puma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puma
  template:
    metadata:
      labels:
        app: puma
    spec:
      containers:
      - name: puma
        image: registry.gitlab.com/8398a7/abilitysheet
        command: ["puma", "-C", "config/puma.rb"]
        envFrom:
        - configMapRef:
            name: rails-config
        - secretRef:
            name: rails-secret
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            port: 3000
      restartPolicy: Always
