apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-deployment
  namespace: abilitysheet
  labels:
    app: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: registry.gitlab.com/8398a7/abilitysheet
        command: ["sidekiq", "-C", "config/sidekiq.yml"]
        envFrom:
        - configMapRef:
            name: rails-config
        - secretRef:
            name: rails-secret
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
      restartPolicy: Always
