default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: abilitysheet

development:
  <<: *default
  database: abilitysheet_development

test:
  <<: *default
  database: abilitysheet_test

production:
  <<: *default
  database: abilitysheet_production
  username: abilitysheet
  password: <%= ENV['ABILITYSHEET_DATABASE_PASSWORD'] %>
