default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: abilitysheet-iidx_development

test:
  <<: *default
  database: abilitysheet-iidx_test

staging:
  <<: *default
  database: abilitysheet-iidx_production
  username: abilitysheet-iidx
  password: <%= ENV['ABILITYSHEET-IIDX_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: abilitysheet-iidx_production
  username: abilitysheet-iidx
  password: <%= ENV['ABILITYSHEET-IIDX_DATABASE_PASSWORD'] %>
