default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: abilitysheet_development

test:
  <<: *default
  database: abilitysheet_test

staging:
  <<: *default
  database: abilitysheet_production
  username: abilitysheet
  password: <%= ENV['ABILITYSHEET_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: abilitysheet_production
  username: abilitysheet
  password: <%= ENV['ABILITYSHEET_DATABASE_PASSWORD'] %>
