:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 5
:queues:
  - manager
  - register
  - iidxme
  - sheet
  - score_viewer
  - sync
  - ist
  - service_dumper
