test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: iidx-app
  credentials: <%= Rails.root.join('service-dumper.json') %>
  bucket: abilitysheet
