apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  namespace: abilitysheet
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  hostPath:
    path: /data
