apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: abilitysheet
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        name: db-migrate
    spec:
      restartPolicy: Never
      containers:
      - name: app
        image: registry.gitlab.com/8398a7/abilitysheet
        command: ["bin/rails", "db:migrate"]
        envFrom:
        - configMapRef:
            name: rails-config
        - secretRef:
            name: rails-secret
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
