name: CI

on: [push]

jobs:
  build:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: echo $REGISTRY_TOKEN | docker login docker.pkg.github.com -u 8398a7 --password-stdin
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - run: make pull build
      - name: initialize gcloud sdk
        run: |
          echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project iidx-app
          gcloud --quiet config set compute/zone us-west1-b
          gcloud auth configure-docker --quiet --project iidx-app
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - run: make push
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
  deploy:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: deploy abilitysheet chart
        run: |
          curl -X POST \
            https://api.github.com/repos/8398a7/iidx-app-cluster/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H "Authorization: Basic ${TOKEN}" \
            -H 'Content-Type: application/json' \
            -d "{\"event_type\": \"abilitysheet abilitysheet.image.tag=$(git describe --tags --abbrev=10)\"}"
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
