name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        if: contains(github.ref, 'master')
      - name: docker login
        run: echo $DOCKER_PASSWORD | docker login -u 8398a7 --password-stdin docker.io
        if: contains(github.ref, 'master')
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull abilitysheet-base
        run: docker pull docker.pkg.github.com/8398a7/abilitysheet/abilitysheet-base:latest
        if: contains(github.ref, 'master')
      - name: build abilitysheet-base
        run: docker build -t docker.pkg.github.com/8398a7/abilitysheet/abilitysheet-base:latest --cache-from docker.pkg.github.com/8398a7/abilitysheet/abilitysheet-base:latest -f build/base.Dockerfile .
        if: contains(github.ref, 'master')
      - name: push abilitysheet-base
        run: docker push docker.pkg.github.com/8398a7/abilitysheet/abilitysheet-base:latest
        if: contains(github.ref, 'master')
      - name: build gcr.io/iidx-app/abilitysheet
        run: docker build -t gcr.io/iidx-app/abilitysheet:$(git describe --tags --abbrev=10) -f build/Dockerfile .
        if: contains(github.ref, 'master')
      - name: initialize gcloud sdk
        run: |
          echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project iidx-app
          gcloud --quiet config set compute/zone us-west1-b
          gcloud auth configure-docker --quiet --project iidx-app
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        if: contains(github.ref, 'master')
      - name: push gcr.io/iidx-app/abilitysheet
        run: docker push gcr.io/iidx-app/abilitysheet:$(git describe --tags --abbrev=10)
        if: contains(github.ref, 'master')
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() && contains(github.ref, 'master')
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: deploy abilitysheet chart
        run: |
          curl -X POST \
            https://api.github.com/repos/8398a7/iidx-app-cluster/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H "Authorization: Basic ${TOKEN}" \
            -H 'Content-Type: application/json' \
            -d "{\"event_type\": \"abilitysheet abilitysheet.image.tag=$(git describe --tags --abbrev=10)\"}"
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        if: contains(github.ref, 'master')
